### ISSUE TITLE
Error Running script

### ISSUE THREAD

**Issue by 3isme** [asolopovas/winconf#2]
Executing script gives following error

`
Error: Call to nonexistent function.

	099: Return ran
	100: }
▶	104: DllCall(RegisterPostMessageHookProc, "Ptr", A_ScriptHwnd, "Int", 0x1400 + 30, "Int")
	105: OnMessage(0x1400 + 30, OnChangeDesktop)
	106: {
`

**Comment by asolopovas** [comment]
Which windows are you on 10 / 11?

**Comment by 3isme** [comment]
Win 11.

**Comment by asolopovas** [comment]
which shortcut have you used to trigger the error? can you send me a screenshot ? I just don't see enough information about the error. I am using the current branch on 2 computers with windows 11 both of them work flawlesly

**Comment by asolopovas** [comment]
you can try replacing VirtualDesktopAccessor.dll with the latest one available at https://github.com/Ciantic/VirtualDesktopAccessor/releases, but its hard to say which it doesn't work on your end without more details.

**Comment by 3isme** [comment]
> which shortcut have you used to trigger the error? can you send me a screenshot ? I just don't see enough information about the error. I am using the current branch on 2 computers with windows 11 both of them work flawlesly

The error occurs when I try to run the script.  I cant get past this.    Also.. I cant get the original version to work on the 1.3 version either.  the script runs but nothing happens when i use the hot keys. so maybe something is wrong with my setup. I will try the .dll

![image](https://github.com/asolopovas/winconf/assets/129439189/e3268897-b686-4186-bec3-1428de0d5b6d)

**Comment by asolopovas** [comment]
show call stack

**Comment by 3isme** [comment]
Call stack:
C:\Users\XXXXXXXX\Documents\AutoHotkey\desktop_switcher.ahk (104) : [DllCall] DllCall(RegisterPostMessageHookProc, "Ptr", A_ScriptHwnd, "Int", 0x1400 + 30, "Int")
C:\Users\XXXXXXXX\Documents\AutoHotkey\desktop_switcher.ahk (104) : [] DllCall(RegisterPostMessageHookProc, "Ptr", A_ScriptHwnd, "Int", 0x1400 + 30, "Int")
> Auto-execute

**Comment by asolopovas** [comment]
It probably doesn't load VirtualDestkopAccessor from the proper path:
`VDA_PATH := A_ScriptDir . "\desktop-switcher\11\VirtualDesktopAccessor.dll"` This is how it finds the dll my dotfiles are located in $env:userprofile\winconf so the path for dll is relative to load.ahk location, which resides in $env:userprofile\winconf\configs\autohotkey-v2\load.ahk, so A_ScriptDir == `$env:userprofile\winconf\configs\autohotkey-v2` the path must be correct, try to alert VDA_PATH variable and see whether it has correct path.

**Comment by asolopovas** [comment]
if this part fails for any reason `hVirtualDesktopAccessor := DllCall("LoadLibrary", "Str", VDA_PATH, "Ptr")` none of the functions will be available.

**Comment by 3isme** [comment]
ive tried your suggestion (among others) debugging, it appears my hot key combinations are working, both scripts start (with debug messages added to the code)  but nothing happens when switching the screen. I am using the lastest version of  VirtualDesktopAccessor.dll,  from their github, and my indicated windows 11 version is, as suggested, later than the dll was built for.    Ive ran the code through open ai a few times with no errors found.  I think maybe something is wrong with the .dll or windows newest update broke it again.   Idk, im at a loss

**Comment by 3isme** [comment]
I found a even newer version of the .dll file here. this corrected the issues for my windows version.

https://github.com/itzjakm/VirtualDesktopAccessor/releases/tag/22635.2915
